server:
  port: 8000
  servlet:
    context-path: /api

spring:
  profiles:
    active: "test"
    
spring.boot.admin.client.url: http://localhost:8001/admin
  

default:
  sender: fernando.nandotania@hotmail.com
  recipient: fernando.nandotania@hotmail.com

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: false

logging:
  file: appfile.log
