server:
  port: 8000
  servlet:
    context-path: /api

spring:
  profiles:
    active: "test"

default:
  sender: fernando.nandotania@hotmail.com
  recipient: fernando.nandotania@hotmail.com

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: true

logging:
  level:
    org.springdoc: DEBUG
