spring:
  application:
    name: library
  mail:
    host: smtp.gmail.com
    username: fdsdejesus@gmail.com
    password: sfusstdmrlgvnbky  # Preencha com a sua senha do Gmail
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
          ssl:
            enable: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    # Para não serializar objetos nulos
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
